/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.uvg_estructuras_algoritmos.radio_de_carro;

/**
 *
 * @author sevic69
 */
public class InterfazDeUsuario extends javax.swing.JFrame 
{
    protected RadioI implementacionRadio;
    
    /**
     * Creates new form InterfazDeUsuario
     */
    public InterfazDeUsuario() 
    {
        initComponents();
        // cambiar esta linea de codigo con la nueva clase para probar
        implementacionRadio = new ImplementacionRadio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ControlesPrincipales = new javax.swing.JPanel();
        scrPn_PantallaRadio = new javax.swing.JScrollPane();
        tA_PantallaRadio = new javax.swing.JTextArea();
        btn_FrecAdelante = new javax.swing.JButton();
        btn_FrecAtras = new javax.swing.JButton();
        tglBtn_PrenderApagar = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        pnl_BotonesMemoria = new javax.swing.JPanel();
        btn_Memoria0 = new javax.swing.JButton();
        btn_Memoria1 = new javax.swing.JButton();
        btn_Memoria2 = new javax.swing.JButton();
        btn_Memoria3 = new javax.swing.JButton();
        btn_Memoria4 = new javax.swing.JButton();
        btn_Memoria5 = new javax.swing.JButton();
        btn_Memoria6 = new javax.swing.JButton();
        btn_Memoria7 = new javax.swing.JButton();
        btn_Memoria8 = new javax.swing.JButton();
        btn_Memoria9 = new javax.swing.JButton();
        btn_Memoria10 = new javax.swing.JButton();
        btn_Memoria11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame_InterfazDeUsuario"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_ControlesPrincipales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrPn_PantallaRadio.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrPn_PantallaRadio.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tA_PantallaRadio.setEditable(false);
        tA_PantallaRadio.setColumns(20);
        tA_PantallaRadio.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        tA_PantallaRadio.setRows(5);
        scrPn_PantallaRadio.setViewportView(tA_PantallaRadio);

        pnl_ControlesPrincipales.add(scrPn_PantallaRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 760, 120));

        btn_FrecAdelante.setLabel(">>");
        pnl_ControlesPrincipales.add(btn_FrecAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 80, 80));

        btn_FrecAtras.setLabel("<<");
        pnl_ControlesPrincipales.add(btn_FrecAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 80, 80));

        tglBtn_PrenderApagar.setText("Prender");
        pnl_ControlesPrincipales.add(tglBtn_PrenderApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        jToggleButton1.setText("AM");
        pnl_ControlesPrincipales.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 80, 80));

        getContentPane().add(pnl_ControlesPrincipales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 180));

        pnl_BotonesMemoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Memoria0.setText("1");
        pnl_BotonesMemoria.add(btn_Memoria0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        btn_Memoria1.setLabel("2");
        pnl_BotonesMemoria.add(btn_Memoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 80));

        btn_Memoria2.setLabel("3");
        pnl_BotonesMemoria.add(btn_Memoria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 80, 80));

        btn_Memoria3.setLabel("4");
        pnl_BotonesMemoria.add(btn_Memoria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 80, 80));

        btn_Memoria4.setLabel("5");
        pnl_BotonesMemoria.add(btn_Memoria4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 80, 80));

        btn_Memoria5.setLabel("6");
        pnl_BotonesMemoria.add(btn_Memoria5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 80, 80));

        btn_Memoria6.setLabel("7");
        pnl_BotonesMemoria.add(btn_Memoria6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 80, 80));

        btn_Memoria7.setLabel("8");
        pnl_BotonesMemoria.add(btn_Memoria7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 80, 80));

        btn_Memoria8.setLabel("9");
        pnl_BotonesMemoria.add(btn_Memoria8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 80, 80));

        btn_Memoria9.setLabel("10");
        pnl_BotonesMemoria.add(btn_Memoria9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 80, 80));

        btn_Memoria10.setLabel("11");
        pnl_BotonesMemoria.add(btn_Memoria10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 80, 80));

        btn_Memoria11.setLabel("12");
        pnl_BotonesMemoria.add(btn_Memoria11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 80, 80));

        getContentPane().add(pnl_BotonesMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 200, 480, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazDeUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_FrecAdelante;
    private javax.swing.JButton btn_FrecAtras;
    private javax.swing.JButton btn_Memoria0;
    private javax.swing.JButton btn_Memoria1;
    private javax.swing.JButton btn_Memoria10;
    private javax.swing.JButton btn_Memoria11;
    private javax.swing.JButton btn_Memoria2;
    private javax.swing.JButton btn_Memoria3;
    private javax.swing.JButton btn_Memoria4;
    private javax.swing.JButton btn_Memoria5;
    private javax.swing.JButton btn_Memoria6;
    private javax.swing.JButton btn_Memoria7;
    private javax.swing.JButton btn_Memoria8;
    private javax.swing.JButton btn_Memoria9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel pnl_BotonesMemoria;
    private javax.swing.JPanel pnl_ControlesPrincipales;
    private javax.swing.JScrollPane scrPn_PantallaRadio;
    private javax.swing.JTextArea tA_PantallaRadio;
    private javax.swing.JToggleButton tglBtn_PrenderApagar;
    // End of variables declaration//GEN-END:variables

}

